name: test2new
description: "A new Flutter module project."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.10.5+5
  path_provider: ^2.0.15 # Hạ cấp để tương thích với ffi 1.0.0 (có thể tflite_flutter < 0.9.2 cần)
  path: ^1.8.3
  http: ^0.13.6
  image: ^3.2.2
  image_picker: ^1.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Thêm assets để chứa model TFLite
  assets:
    - assets/models/gesture_model.tflite
    - assets/label_mapping.json
    
  module:
    androidX: true
    androidPackage: com.example.test2new
    iosBundleIdentifier: com.example.test2new